steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
  - '-c'
  - |
    echo "enter 1 bash commannd from GitHub"
    sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    sudo apt-get update && sudo apt-get install terraform
    terraform -v
    #gcloud version
    #pwd
    #whoami
    
    
    #https://learn.hashicorp.com/tutorials/terraform/install-cli?in=terraform/gcp-get-started



